# Generated by Django 5.0.3 on 2024-04-08 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_autor', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome_autor'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarios_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('numeroRA', models.CharField(max_length=30)),
                ('situacaoaluno', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=20, unique=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nome_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videos_id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.CharField(max_length=100)),
                ('nome_video', models.CharField(max_length=100, verbose_name='Nome do Video ')),
                ('qtvideos', models.BigIntegerField()),
                ('estante', models.CharField(blank=True, max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nome_video'],
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('livros_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do livro')),
                ('qtlivros', models.BigIntegerField()),
                ('estante', models.CharField(max_length=100)),
                ('tipostatus', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Outros', 'Outros')], default='Aluno', max_length=30, verbose_name='Status do livro')),
                ('edicao', models.CharField(blank=True, max_length=100)),
                ('assunto', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.autores')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('emprestimo_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('livros_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_livro', to='todos.livros')),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.usuarios')),
            ],
            options={
                'ordering': ['data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='EmprestimoVideo',
            fields=[
                ('emprestimo_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.usuarios')),
                ('videos_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_video', to='todos.videos')),
            ],
            options={
                'ordering': ['data_emprestimo'],
            },
        ),
    ]
