# Generated by Django 5.0.4 on 2024-04-27 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='nome_autor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Autor '),
        ),
        migrations.AlterField(
            model_name='emprestimolivro',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução: '),
        ),
        migrations.AlterField(
            model_name='emprestimolivro',
            name='data_emprestimo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo: '),
        ),
        migrations.AlterField(
            model_name='emprestimolivro',
            name='livros_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_livro', to='todos.livros', verbose_name='Nome do Livro: '),
        ),
        migrations.AlterField(
            model_name='emprestimolivro',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.usuarios', verbose_name='Nome do usuário: '),
        ),
        migrations.AlterField(
            model_name='emprestimovideo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução: '),
        ),
        migrations.AlterField(
            model_name='emprestimovideo',
            name='data_emprestimo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo: '),
        ),
        migrations.AlterField(
            model_name='emprestimovideo',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.usuarios', verbose_name='Nome do Usuário: '),
        ),
        migrations.AlterField(
            model_name='emprestimovideo',
            name='videos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_video', to='todos.videos', verbose_name='Nome do Video: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='assunto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assunto: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.autores', verbose_name='Nome do autor '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Cadastro: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='edicao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edição: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='estante',
            field=models.CharField(max_length=100, verbose_name='Estante de Arquivo: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='qtlivros',
            field=models.BigIntegerField(verbose_name='Quantidade de Livros: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='tipostatus',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Outros', 'Outros')], default='Aluno', max_length=30, verbose_name='Status do aluno: '),
        ),
        migrations.AlterField(
            model_name='livros',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título do livro: '),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome_usuario',
            field=models.CharField(max_length=100, verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numeroRA',
            field=models.CharField(max_length=30, verbose_name='Número do RA'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='serie',
            field=models.CharField(max_length=20, unique=True, verbose_name='Série do Aluno:'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='situacaoaluno',
            field=models.CharField(max_length=30, verbose_name='Situação do Aluno:'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='colecao',
            field=models.CharField(max_length=100, verbose_name='Coleção '),
        ),
        migrations.AlterField(
            model_name='videos',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Cadastro '),
        ),
        migrations.AlterField(
            model_name='videos',
            name='estante',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome da estante:'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='nome_video',
            field=models.CharField(max_length=100, verbose_name='Nome do Video'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação '),
        ),
        migrations.AlterField(
            model_name='videos',
            name='qtvideos',
            field=models.BigIntegerField(verbose_name='Quantidade de Videos: '),
        ),
    ]
